canton {
  mediators {
    mediator {
      admin-api.address = 0.0.0.0
      admin-api.port = 5007
    }
  }
  sequencers {
    sequencer {
      public-api.address = 0.0.0.0
      public-api.port = 5008
      admin-api.address = 0.0.0.0
      admin-api.port = 5009
    }
  }
  participants {
    participant {
      ledger-api.address = 0.0.0.0
      ledger-api.port = 5001
      admin-api.address = 0.0.0.0
      admin-api.port = 5002
    }
  }
}