canton {
  remote-mediators {
    mediator {
      admin-api.address = canton
      admin-api.port = 5009
    }
  }
  remote-sequencers {
    sequencer {
      public-api.address = canton
      public-api.port = 5008
      admin-api.address = canton
      admin-api.port = 5009
    }
  }
  remote-participants {
    participant {
      ledger-api.port = 5001
      ledger-api.address = canton
      admin-api.port = 5002
      admin-api.address = canton
    }
  }
}