services:

  mydomain:
    container_name: mydomain
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.9.5
    volumes:
      - ./configs:/canton/host/configs:r
    command: daemon --config "/canton/host/configs/mydomain.conf" --log-profile container --log-level-stdout INFO

  participant1:
    container_name: participant1
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.9.5
    volumes:
      - ./configs:/canton/host/configs:r
      - ./.daml/dist/:/canton/host/dist/:r
    command: daemon --config "/canton/host/configs/participant1.conf" --bootstrap "/canton/host/configs/participant1.canton" --log-profile container --log-level-stdout INFO
    healthcheck:
      test: [ "CMD", "/usr/local/bin/grpc_health_probe", "--addr", "participant1:5861" ]
    depends_on:
      - mydomain

  mockauth:
    container_name: mockauth
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    volumes:
      - ./configs:/configs
    environment:
      - SERVER_PORT=80
      - JSON_CONFIG_PATH=/configs/mockauth.json
    ports:
      - "8081:80"
    depends_on:
      participant1:
        condition: service_healthy

  pqs_db:
    container_name: pqs_db
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DATABASE=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
    ports:
      - 5432:5432

  pqs:
    container_name: pqs
    image: digitalasset-docker.jfrog.io/participant-query-store:0.5.0
    volumes:
      - ./configs:/canton/host/configs:r
    command: pipeline ledger postgres-document --config /canton/host/configs/pqs.conf --pipeline-datasource TransactionTreeStream
    environment:
      - OTEL_JAVAAGENT_ENABLED=false
    depends_on:
      pqs_db:
        condition: service_healthy
      participant1:
        condition: service_healthy
      mockauth:
        condition: service_started

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - pqs_db
      - pqs
    environment:
      - ADMINER_DEFAULT_SERVER=pqs_db
    ports:
      - 8080:8080
