canton.features.enable-testing-commands = yes
canton.remote-participants.participant {
  token = "eyJraWQiOiJtb2NrYXV0aCIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJwYXJ0aWNpcGFudF9hZG1pbiIsImF1ZCI6Imh0dHBzOi8vZGFtbC5jb20vand0L2F1ZC9wYXJ0aWNpcGFudC9zYW5kYm94OjoxMjIwNmM0YTVhZGFlZWY1NDFiZTY4Njg1ZjYxYzkxYWExYzRlOGY2M2Y2NmY5YjllYjNhMjVhMjg5YmFhMmQxMGU2MyIsIm5iZiI6MTc0OTU4NDY2OCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL21vY2thdXRoIiwiZXhwIjoxNzUwMTg5NDY4LCJpYXQiOjE3NDk1ODQ2NjgsImp0aSI6IjQ2Yjk5YjdiLWNlMGEtNGJjOS04ODc3LTg3MzBjMzkwMTExYiJ9.BPAvwLrIVl1Cx9ljBjBqQoVW0fnFrR_CqlKPO8omJRFMdD_x7Sds-gd76fTMz5aQtvYCqxeD9qVN9oKBOcZiwiLnMtYnsd3b9P3JAKQV_tPIIdcuT9YRnN6s4zRRejLOyd1AOd1iauDL3DpkPo6JPv6wO776Grq6NFZKZU4BXgD2WOppPkX0AoYqU11Hna1ChFnvvZtzuc4tkO2-jjtmQ7MdSUWfmhY5HUqby9LtenLTsAVQRi_sLFkQMk7KDy2ZSLQr-OayJCICLTpVfX62GZhN_LW_V_4px3SHWLMv6DttnWhHoafg2A4fTvg37BjXUhQR1eb_qUOpCYcxm1P9LA"
  ledger-api {
    address = "localhost"
    port = "6865"
  }
  admin-api {
    address = "localhost"
    port = "6866"
  }
}