canton.features.enable-testing-commands = yes
canton.remote-participants.participant {
  token = "<jwt token here>"
  ledger-api {
    address = "localhost"
    port = "6865"
  }
  admin-api {
    address = "localhost"
    port = "6866"
  }
}